//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonResources.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_IO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_IO() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonResources.Properties.Resources_IO", typeof(Resources_IO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DI6PLA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DI6PLA {
            get {
                return ResourceManager.GetString("DI6PLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DI8PLA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DI8PLA {
            get {
                return ResourceManager.GetString("DI8PLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DI8PRS1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DI8PRS1 {
            get {
                return ResourceManager.GetString("DI8PRS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DI8PRS2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DI8PRS2 {
            get {
                return ResourceManager.GetString("DI8PRS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DI8PRS3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DI8PRS3 {
            get {
                return ResourceManager.GetString("DI8PRS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIARM1VAC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARM1VAC {
            get {
                return ResourceManager.GetString("DIARM1VAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIARM2VAC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARM2VAC {
            get {
                return ResourceManager.GetString("DIARM2VAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIARMIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARMIN {
            get {
                return ResourceManager.GetString("DIARMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIARMOUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIARMOUT {
            get {
                return ResourceManager.GetString("DIARMOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIBeamLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIBeamLOCK {
            get {
                return ResourceManager.GetString("DIBeamLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIBeamLOCK_2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIBeamLOCK_2 {
            get {
                return ResourceManager.GetString("DIBeamLOCK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIBeamUnLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIBeamUnLOCK {
            get {
                return ResourceManager.GetString("DIBeamUnLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIBeamUnLOCK_2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIBeamUnLOCK_2 {
            get {
                return ResourceManager.GetString("DIBeamUnLOCK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICard_Holder_Detect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICard_Holder_Detect {
            get {
                return ResourceManager.GetString("DICard_Holder_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDCHANGE_IDLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDCHANGE_IDLE {
            get {
                return ResourceManager.GetString("DICARDCHANGE_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDCHANGE_IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDCHANGE_IN {
            get {
                return ResourceManager.GetString("DICARDCHANGE_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDCHANGE_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDCHANGE_OUT {
            get {
                return ResourceManager.GetString("DICARDCHANGE_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDHOLDERCLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDHOLDERCLOSE {
            get {
                return ResourceManager.GetString("DICARDHOLDERCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDHOLDERLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDHOLDERLOCK {
            get {
                return ResourceManager.GetString("DICARDHOLDERLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDHOLDEROPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDHOLDEROPEN {
            get {
                return ResourceManager.GetString("DICARDHOLDEROPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDHOLDERUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDHOLDERUP {
            get {
                return ResourceManager.GetString("DICARDHOLDERUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDMOVEINDONE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDMOVEINDONE {
            get {
                return ResourceManager.GetString("DICARDMOVEINDONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDMOVEOUTDONE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDMOVEOUTDONE {
            get {
                return ResourceManager.GetString("DICARDMOVEOUTDONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICardOnPlateL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICardOnPlateL {
            get {
                return ResourceManager.GetString("DICardOnPlateL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICardOnPlateM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICardOnPlateM {
            get {
                return ResourceManager.GetString("DICardOnPlateM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICardOnPlateR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICardOnPlateR {
            get {
                return ResourceManager.GetString("DICardOnPlateR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDTRAY_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDTRAY_LOCK {
            get {
                return ResourceManager.GetString("DICARDTRAY_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARDTRAY_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARDTRAY_UNLOCK {
            get {
                return ResourceManager.GetString("DICARDTRAY_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARRIER_LOCK_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARRIER_LOCK_0 {
            get {
                return ResourceManager.GetString("DICARRIER_LOCK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARRIER_LOCK_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARRIER_LOCK_1 {
            get {
                return ResourceManager.GetString("DICARRIER_LOCK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICARRIER_POS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICARRIER_POS {
            get {
                return ResourceManager.GetString("DICARRIER_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICH_CARRIER_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICH_CARRIER_UP {
            get {
                return ResourceManager.GetString("DICH_CARRIER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICH_ROT_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICH_ROT_CLOSE {
            get {
                return ResourceManager.GetString("DICH_ROT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICH_ROT_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICH_ROT_OPEN {
            get {
                return ResourceManager.GetString("DICH_ROT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICH_TUB_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICH_TUB_CLOSE {
            get {
                return ResourceManager.GetString("DICH_TUB_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICH_TUB_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICH_TUB_OPEN {
            get {
                return ResourceManager.GetString("DICH_TUB_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICHECK_WAFER_ON_ARM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICHECK_WAFER_ON_ARM {
            get {
                return ResourceManager.GetString("DICHECK_WAFER_ON_ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICHECK_WAFER_ON_PRE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICHECK_WAFER_ON_PRE {
            get {
                return ResourceManager.GetString("DICHECK_WAFER_ON_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICHECK_WAFER_OUT_ON_CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICHECK_WAFER_OUT_ON_CST {
            get {
                return ResourceManager.GetString("DICHECK_WAFER_OUT_ON_CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICHUCK_SAFE_CMD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICHUCK_SAFE_CMD {
            get {
                return ResourceManager.GetString("DICHUCK_SAFE_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLEANUNITUP_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLEANUNITUP_0 {
            get {
                return ResourceManager.GetString("DICLEANUNITUP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLEANUNITUP_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLEANUNITUP_1 {
            get {
                return ResourceManager.GetString("DICLEANUNITUP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLEANUNITVAC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLEANUNITVAC {
            get {
                return ResourceManager.GetString("DICLEANUNITVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLEANWAFERONDRAWER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLEANWAFERONDRAWER {
            get {
                return ResourceManager.GetString("DICLEANWAFERONDRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLP_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLP_LOCK {
            get {
                return ResourceManager.GetString("DICLP_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICLP_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICLP_UNLOCK {
            get {
                return ResourceManager.GetString("DICLP_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICOOLANT_LOW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICOOLANT_LOW {
            get {
                return ResourceManager.GetString("DICOOLANT_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICSTPORTCLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICSTPORTCLOSE {
            get {
                return ResourceManager.GetString("DICSTPORTCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICSTSIZE_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICSTSIZE_0 {
            get {
                return ResourceManager.GetString("DICSTSIZE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICSTSIZE_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICSTSIZE_1 {
            get {
                return ResourceManager.GetString("DICSTSIZE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICSTSIZE_2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DICSTSIZE_2 {
            get {
                return ResourceManager.GetString("DICSTSIZE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDD_FRONT_INNER_COVER_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDD_FRONT_INNER_COVER_CLOSE {
            get {
                return ResourceManager.GetString("DIDD_FRONT_INNER_COVER_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDD_FRONT_INNER_COVER_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDD_FRONT_INNER_COVER_OPEN {
            get {
                return ResourceManager.GetString("DIDD_FRONT_INNER_COVER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDOORCLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDOORCLOSE {
            get {
                return ResourceManager.GetString("DIDOORCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDRAWEREMOVED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDRAWEREMOVED {
            get {
                return ResourceManager.GetString("DIDRAWEREMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDRAWEROPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDRAWEROPEN {
            get {
                return ResourceManager.GetString("DIDRAWEROPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIDRY_AIR_PRSSURE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIDRY_AIR_PRSSURE {
            get {
                return ResourceManager.GetString("DIDRY_AIR_PRSSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIEMGSTOPSW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIEMGSTOPSW {
            get {
                return ResourceManager.GetString("DIEMGSTOPSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_NOTCH1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_NOTCH1 {
            get {
                return ResourceManager.GetString("DIFD_NOTCH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_NOTCH2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_NOTCH2 {
            get {
                return ResourceManager.GetString("DIFD_NOTCH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_PREIN_FRONT_IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_PREIN_FRONT_IN {
            get {
                return ResourceManager.GetString("DIFD_PREIN_FRONT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_PREIN_FRONT_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_PREIN_FRONT_OUT {
            get {
                return ResourceManager.GetString("DIFD_PREIN_FRONT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_PREIN_REAR_IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_PREIN_REAR_IN {
            get {
                return ResourceManager.GetString("DIFD_PREIN_REAR_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_PREIN_REAR_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_PREIN_REAR_OUT {
            get {
                return ResourceManager.GetString("DIFD_PREIN_REAR_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_SUBCHUCK_ON_WAFER1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_SUBCHUCK_ON_WAFER1 {
            get {
                return ResourceManager.GetString("DIFD_SUBCHUCK_ON_WAFER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_SUBCHUCK_ON_WAFER2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_SUBCHUCK_ON_WAFER2 {
            get {
                return ResourceManager.GetString("DIFD_SUBCHUCK_ON_WAFER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_THREE_LEGDN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_THREE_LEGDN {
            get {
                return ResourceManager.GetString("DIFD_THREE_LEGDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFD_THREE_LEGUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFD_THREE_LEGUP {
            get {
                return ResourceManager.GetString("DIFD_THREE_LEGUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFDOOR_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFDOOR_CLOSE {
            get {
                return ResourceManager.GetString("DIFDOOR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFDOOR_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFDOOR_OPEN {
            get {
                return ResourceManager.GetString("DIFDOOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFOUP_COVER_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFOUP_COVER_LOCK {
            get {
                return ResourceManager.GetString("DIFOUP_COVER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFOUP_COVER_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFOUP_COVER_UNLOCK {
            get {
                return ResourceManager.GetString("DIFOUP_COVER_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFOUPSWINGSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFOUPSWINGSENSOR {
            get {
                return ResourceManager.GetString("DIFOUPSWINGSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRAMEDONSUBCHUCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRAMEDONSUBCHUCK {
            get {
                return ResourceManager.GetString("DIFRAMEDONSUBCHUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRAMEDPREDN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRAMEDPREDN {
            get {
                return ResourceManager.GetString("DIFRAMEDPREDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRAMEDPREIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRAMEDPREIN {
            get {
                return ResourceManager.GetString("DIFRAMEDPREIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRAMEDPREOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRAMEDPREOT {
            get {
                return ResourceManager.GetString("DIFRAMEDPREOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRAMEDPREUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRAMEDPREUP {
            get {
                return ResourceManager.GetString("DIFRAMEDPREUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRONT_DOOR_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONT_DOOR_OPEN {
            get {
                return ResourceManager.GetString("DIFRONT_DOOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRONTDOOR_LOCK_L과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOOR_LOCK_L {
            get {
                return ResourceManager.GetString("DIFRONTDOOR_LOCK_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRONTDOOR_LOCK_R과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOOR_LOCK_R {
            get {
                return ResourceManager.GetString("DIFRONTDOOR_LOCK_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRONTDOOR_UNLOCK_L과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOOR_UNLOCK_L {
            get {
                return ResourceManager.GetString("DIFRONTDOOR_UNLOCK_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIFRONTDOOR_UNLOCK_R과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOOR_UNLOCK_R {
            get {
                return ResourceManager.GetString("DIFRONTDOOR_UNLOCK_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [I] Front Door Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOORCLOSE {
            get {
                return ResourceManager.GetString("DIFRONTDOORCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [I] Front Door Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIFRONTDOOROPEN {
            get {
                return ResourceManager.GetString("DIFRONTDOOROPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIHardDockActive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIHardDockActive {
            get {
                return ResourceManager.GetString("DIHardDockActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIHEATER_FAIL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIHEATER_FAIL {
            get {
                return ResourceManager.GetString("DIHEATER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIHOMEII_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIHOMEII_0 {
            get {
                return ResourceManager.GetString("DIHOMEII_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIHOMEII_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIHOMEII_1 {
            get {
                return ResourceManager.GetString("DIHOMEII_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIINKERDOWN_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIINKERDOWN_0 {
            get {
                return ResourceManager.GetString("DIINKERDOWN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIINKERDOWN_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIINKERDOWN_1 {
            get {
                return ResourceManager.GetString("DIINKERDOWN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIINSPECTION_COVER_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIINSPECTION_COVER_LOCK {
            get {
                return ResourceManager.GetString("DIINSPECTION_COVER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIINSPECTION_COVER_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIINSPECTION_COVER_UNLOCK {
            get {
                return ResourceManager.GetString("DIINSPECTION_COVER_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DILATCHED_VERIFY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DILATCHED_VERIFY {
            get {
                return ResourceManager.GetString("DILATCHED_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DILDOOR_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DILDOOR_CLOSE {
            get {
                return ResourceManager.GetString("DILDOOR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DILDOOR_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DILDOOR_OPEN {
            get {
                return ResourceManager.GetString("DILDOOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DILOADERDOOR_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DILOADERDOOR_CLOSE {
            get {
                return ResourceManager.GetString("DILOADERDOOR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DILOADERDOOR_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DILOADERDOOR_OPEN {
            get {
                return ResourceManager.GetString("DILOADERDOOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMAINAIR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMAINAIR {
            get {
                return ResourceManager.GetString("DIMAINAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMAINVAC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMAINVAC {
            get {
                return ResourceManager.GetString("DIMAINVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMANIPULATOR_READY_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMANIPULATOR_READY_0 {
            get {
                return ResourceManager.GetString("DIMANIPULATOR_READY_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMANIPULATOR_READY_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMANIPULATOR_READY_1 {
            get {
                return ResourceManager.GetString("DIMANIPULATOR_READY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMANIPULATORREADY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMANIPULATORREADY {
            get {
                return ResourceManager.GetString("DIMANIPULATORREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMB_440과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMB_440 {
            get {
                return ResourceManager.GetString("DIMB_440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMB_480과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMB_480 {
            get {
                return ResourceManager.GetString("DIMB_480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMB_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMB_LOCK {
            get {
                return ResourceManager.GetString("DIMB_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIMECH_CLAMP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIMECH_CLAMP {
            get {
                return ResourceManager.GetString("DIMECH_CLAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DINC_SENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DINC_SENSOR {
            get {
                return ResourceManager.GetString("DINC_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DINCPAD_VAC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DINCPAD_VAC {
            get {
                return ResourceManager.GetString("DINCPAD_VAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DINEEDLE_BRUSH_DN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DINEEDLE_BRUSH_DN {
            get {
                return ResourceManager.GetString("DINEEDLE_BRUSH_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DINEEDLE_BRUSH_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DINEEDLE_BRUSH_UP {
            get {
                return ResourceManager.GetString("DINEEDLE_BRUSH_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DINO_CLAMP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DINO_CLAMP {
            get {
                return ResourceManager.GetString("DINO_CLAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIPlateSwingDownPOS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIPlateSwingDownPOS {
            get {
                return ResourceManager.GetString("DIPlateSwingDownPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIPlateSwingUpPOS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIPlateSwingUpPOS {
            get {
                return ResourceManager.GetString("DIPlateSwingUpPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIPOWER_DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIPOWER_DOWN {
            get {
                return ResourceManager.GetString("DIPOWER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIPROBE_CARD_PRESENTED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIPROBE_CARD_PRESENTED {
            get {
                return ResourceManager.GetString("DIPROBE_CARD_PRESENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCAN_SENSOR_IN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISCAN_SENSOR_IN {
            get {
                return ResourceManager.GetString("DISCAN_SENSOR_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCAN_SENSOR_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISCAN_SENSOR_OUT {
            get {
                return ResourceManager.GetString("DISCAN_SENSOR_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCANMAPPINGSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISCANMAPPINGSENSOR {
            get {
                return ResourceManager.GetString("DISCANMAPPINGSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISoftDockActive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISoftDockActive {
            get {
                return ResourceManager.GetString("DISoftDockActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISPARE0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISPARE0 {
            get {
                return ResourceManager.GetString("DISPARE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISPARE1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISPARE1 {
            get {
                return ResourceManager.GetString("DISPARE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIStiffDetect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIStiffDetect {
            get {
                return ResourceManager.GetString("DIStiffDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIStiffOpen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIStiffOpen {
            get {
                return ResourceManager.GetString("DIStiffOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISUBCHUCKVACSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DISUBCHUCKVACSENSOR {
            get {
                return ResourceManager.GetString("DISUBCHUCKVACSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_CLAMP_MID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_CLAMP_MID {
            get {
                return ResourceManager.GetString("DIT2K_CLAMP_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_CLAMP_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_CLAMP_UP {
            get {
                return ResourceManager.GetString("DIT2K_CLAMP_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_CYLINDER_DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_CYLINDER_DOWN {
            get {
                return ResourceManager.GetString("DIT2K_CYLINDER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_CYLINDER_MID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_CYLINDER_MID {
            get {
                return ResourceManager.GetString("DIT2K_CYLINDER_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_CYLINDER_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_CYLINDER_UP {
            get {
                return ResourceManager.GetString("DIT2K_CYLINDER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_PROBECARD_MID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_PROBECARD_MID {
            get {
                return ResourceManager.GetString("DIT2K_PROBECARD_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIT2K_PROBECARD_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIT2K_PROBECARD_UP {
            get {
                return ResourceManager.GetString("DIT2K_PROBECARD_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_DOCK_SENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_DOCK_SENSOR {
            get {
                return ResourceManager.GetString("DITESTER_DOCK_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_EMERGENCY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_EMERGENCY {
            get {
                return ResourceManager.GetString("DITESTER_EMERGENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_HEAD_DOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_HEAD_DOCK {
            get {
                return ResourceManager.GetString("DITESTER_HEAD_DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_HEAD_HORI과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_HEAD_HORI {
            get {
                return ResourceManager.GetString("DITESTER_HEAD_HORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_RDY_FOR_PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_RDY_FOR_PC {
            get {
                return ResourceManager.GetString("DITESTER_RDY_FOR_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITESTER_VACUUM_READY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITESTER_VACUUM_READY {
            get {
                return ResourceManager.GetString("DITESTER_VACUUM_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITH_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITH_LOCK {
            get {
                return ResourceManager.GetString("DITH_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITH_MBLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITH_MBLOCK {
            get {
                return ResourceManager.GetString("DITH_MBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITH_PBLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITH_PBLOCK {
            get {
                return ResourceManager.GetString("DITH_PBLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITH_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITH_UNLOCK {
            get {
                return ResourceManager.GetString("DITH_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITHREELEGUP_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITHREELEGUP_0 {
            get {
                return ResourceManager.GetString("DITHREELEGUP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITHREELEGUP_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITHREELEGUP_1 {
            get {
                return ResourceManager.GetString("DITHREELEGUP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITOPPLATE_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITOPPLATE_CLOSE {
            get {
                return ResourceManager.GetString("DITOPPLATE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITOPPLATE_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITOPPLATE_OPEN {
            get {
                return ResourceManager.GetString("DITOPPLATE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITP_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITP_LOCK {
            get {
                return ResourceManager.GetString("DITP_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITP_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITP_UNLOCK {
            get {
                return ResourceManager.GetString("DITP_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DITRAYDETECTSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DITRAYDETECTSENSOR {
            get {
                return ResourceManager.GetString("DITRAYDETECTSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIUNLATCHED_VERIFY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIUNLATCHED_VERIFY {
            get {
                return ResourceManager.GetString("DIUNLATCHED_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIV93K_POGO_DUT_DOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIV93K_POGO_DUT_DOCK {
            get {
                return ResourceManager.GetString("DIV93K_POGO_DUT_DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERCAMMIDDLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERCAMMIDDLE {
            get {
                return ResourceManager.GetString("DIWAFERCAMMIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERCAMREAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERCAMREAL {
            get {
                return ResourceManager.GetString("DIWAFERCAMREAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERDETECTSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERDETECTSENSOR {
            get {
                return ResourceManager.GetString("DIWAFERDETECTSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONARM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONARM {
            get {
                return ResourceManager.GetString("DIWAFERONARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONARM2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONARM2 {
            get {
                return ResourceManager.GetString("DIWAFERONARM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONCHUCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONCHUCK {
            get {
                return ResourceManager.GetString("DIWAFERONCHUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONCHUCK_12과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONCHUCK_12 {
            get {
                return ResourceManager.GetString("DIWAFERONCHUCK_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONCHUCK_6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONCHUCK_6 {
            get {
                return ResourceManager.GetString("DIWAFERONCHUCK_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONCHUCK_8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONCHUCK_8 {
            get {
                return ResourceManager.GetString("DIWAFERONCHUCK_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONDRAWER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONDRAWER {
            get {
                return ResourceManager.GetString("DIWAFERONDRAWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONFIXEDTRAY0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONFIXEDTRAY0 {
            get {
                return ResourceManager.GetString("DIWAFERONFIXEDTRAY0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONFIXEDTRAY1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONFIXEDTRAY1 {
            get {
                return ResourceManager.GetString("DIWAFERONFIXEDTRAY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONFIXEDTRAY2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONFIXEDTRAY2 {
            get {
                return ResourceManager.GetString("DIWAFERONFIXEDTRAY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONFIXEDTRAY3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONFIXEDTRAY3 {
            get {
                return ResourceManager.GetString("DIWAFERONFIXEDTRAY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONFIXEDTRAY4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONFIXEDTRAY4 {
            get {
                return ResourceManager.GetString("DIWAFERONFIXEDTRAY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERONSUBCHUCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERONSUBCHUCK {
            get {
                return ResourceManager.GetString("DIWAFERONSUBCHUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERSENSOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERSENSOR {
            get {
                return ResourceManager.GetString("DIWAFERSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIWAFERSLOTOUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIWAFERSLOTOUT {
            get {
                return ResourceManager.GetString("DIWAFERSLOTOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIZIF_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIZIF_LOCK {
            get {
                return ResourceManager.GetString("DIZIF_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DIZIF_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DIZIF_UNLOCK {
            get {
                return ResourceManager.GetString("DIZIF_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOACS_INTERFACE_SIGNAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOACS_INTERFACE_SIGNAL {
            get {
                return ResourceManager.GetString("DOACS_INTERFACE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARM1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARM1 {
            get {
                return ResourceManager.GetString("DOARM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARM2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARM2 {
            get {
                return ResourceManager.GetString("DOARM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARM2AIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARM2AIRON {
            get {
                return ResourceManager.GetString("DOARM2AIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARMAIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARMAIRON {
            get {
                return ResourceManager.GetString("DOARMAIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARMAUXAIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARMAUXAIRON {
            get {
                return ResourceManager.GetString("DOARMAUXAIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARMINAIR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARMINAIR {
            get {
                return ResourceManager.GetString("DOARMINAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOARMOUTAIR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOARMOUTAIR {
            get {
                return ResourceManager.GetString("DOARMOUTAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOBLUELAMPON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOBLUELAMPON {
            get {
                return ResourceManager.GetString("DOBLUELAMPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOBLUELAMPON2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOBLUELAMPON2 {
            get {
                return ResourceManager.GetString("DOBLUELAMPON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOBridgeBeamLock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOBridgeBeamLock {
            get {
                return ResourceManager.GetString("DOBridgeBeamLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOBridgeBeamUnLock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOBridgeBeamUnLock {
            get {
                return ResourceManager.GetString("DOBridgeBeamUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOBUZZERON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOBUZZERON {
            get {
                return ResourceManager.GetString("DOBUZZERON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCAMERA_MUX_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCAMERA_MUX_0 {
            get {
                return ResourceManager.GetString("DOCAMERA_MUX_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCAMERA_MUX_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCAMERA_MUX_1 {
            get {
                return ResourceManager.GetString("DOCAMERA_MUX_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCAMERA_MUX_2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCAMERA_MUX_2 {
            get {
                return ResourceManager.GetString("DOCAMERA_MUX_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCARDHOLDERCLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCARDHOLDERCLOSE {
            get {
                return ResourceManager.GetString("DOCARDHOLDERCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCARDHOLDEROPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCARDHOLDEROPEN {
            get {
                return ResourceManager.GetString("DOCARDHOLDEROPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCARDTRAY_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCARDTRAY_UNLOCK {
            get {
                return ResourceManager.GetString("DOCARDTRAY_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCARRIER_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCARRIER_LOCK {
            get {
                return ResourceManager.GetString("DOCARRIER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCASSETTELOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCASSETTELOCK {
            get {
                return ResourceManager.GetString("DOCASSETTELOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCCMoveInMotorEnable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCCMoveInMotorEnable {
            get {
                return ResourceManager.GetString("DOCCMoveInMotorEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCCMoveOutMotorEnable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCCMoveOutMotorEnable {
            get {
                return ResourceManager.GetString("DOCCMoveOutMotorEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCH_ROT_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCH_ROT_CLOSE {
            get {
                return ResourceManager.GetString("DOCH_ROT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCH_ROT_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCH_ROT_OPEN {
            get {
                return ResourceManager.GetString("DOCH_ROT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCH_TUB_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCH_TUB_CLOSE {
            get {
                return ResourceManager.GetString("DOCH_TUB_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCH_TUB_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCH_TUB_OPEN {
            get {
                return ResourceManager.GetString("DOCH_TUB_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHILLER_ENABLE_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHILLER_ENABLE_0 {
            get {
                return ResourceManager.GetString("DOCHILLER_ENABLE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHILLER_ENABLE_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHILLER_ENABLE_1 {
            get {
                return ResourceManager.GetString("DOCHILLER_ENABLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCK_FG_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCK_FG_OPEN {
            get {
                return ResourceManager.GetString("DOCHUCK_FG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCK_SAFE_STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCK_SAFE_STATUS {
            get {
                return ResourceManager.GetString("DOCHUCK_SAFE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCKAIRON_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCKAIRON_0 {
            get {
                return ResourceManager.GetString("DOCHUCKAIRON_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCKAIRON_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCKAIRON_1 {
            get {
                return ResourceManager.GetString("DOCHUCKAIRON_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCKAIRON_2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCKAIRON_2 {
            get {
                return ResourceManager.GetString("DOCHUCKAIRON_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCKCOOLAIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCKCOOLAIRON {
            get {
                return ResourceManager.GetString("DOCHUCKCOOLAIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCHUCKTEMP_AIR_ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCHUCKTEMP_AIR_ON {
            get {
                return ResourceManager.GetString("DOCHUCKTEMP_AIR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCLEAN_AIR_ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCLEAN_AIR_ON {
            get {
                return ResourceManager.GetString("DOCLEAN_AIR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCLEANUNITUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCLEANUNITUP {
            get {
                return ResourceManager.GetString("DOCLEANUNITUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCLK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCLK {
            get {
                return ResourceManager.GetString("DOCLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCLP_LOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCLP_LOCK_REQ {
            get {
                return ResourceManager.GetString("DOCLP_LOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCLP_UNLOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCLP_UNLOCK_REQ {
            get {
                return ResourceManager.GetString("DOCLP_UNLOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCOLD_CHUCK_AIR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCOLD_CHUCK_AIR {
            get {
                return ResourceManager.GetString("DOCOLD_CHUCK_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCOOLANT_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCOOLANT_OUT {
            get {
                return ResourceManager.GetString("DOCOOLANT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCOOLANT_VALVE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCOOLANT_VALVE {
            get {
                return ResourceManager.GetString("DOCOOLANT_VALVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCSTREADYLAMPON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOCSTREADYLAMPON {
            get {
                return ResourceManager.GetString("DOCSTREADYLAMPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DODATA과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DODATA {
            get {
                return ResourceManager.GetString("DODATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DODD_FRONT_INNER_COVER_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DODD_FRONT_INNER_COVER_OPEN {
            get {
                return ResourceManager.GetString("DODD_FRONT_INNER_COVER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DODD_SWING_DN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DODD_SWING_DN {
            get {
                return ResourceManager.GetString("DODD_SWING_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DODD_SWING_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DODD_SWING_UP {
            get {
                return ResourceManager.GetString("DODD_SWING_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DODRY_AIR_ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DODRY_AIR_ON {
            get {
                return ResourceManager.GetString("DODRY_AIR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOEMGStopForCCMCU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOEMGStopForCCMCU {
            get {
                return ResourceManager.GetString("DOEMGStopForCCMCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFAN_CONTROL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFAN_CONTROL {
            get {
                return ResourceManager.GetString("DOFAN_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFD_PREIN_FRONT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFD_PREIN_FRONT {
            get {
                return ResourceManager.GetString("DOFD_PREIN_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFD_PREIN_REAR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFD_PREIN_REAR {
            get {
                return ResourceManager.GetString("DOFD_PREIN_REAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFD_THREE_LEGUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFD_THREE_LEGUP {
            get {
                return ResourceManager.GetString("DOFD_THREE_LEGUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFDOOR_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFDOOR_LOCK {
            get {
                return ResourceManager.GetString("DOFDOOR_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFDOOR_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFDOOR_UNLOCK {
            get {
                return ResourceManager.GetString("DOFDOOR_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFOUP_COVER_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFOUP_COVER_LOCK {
            get {
                return ResourceManager.GetString("DOFOUP_COVER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFOUPSWING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFOUPSWING {
            get {
                return ResourceManager.GetString("DOFOUPSWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFRAMEDPREIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFRAMEDPREIN {
            get {
                return ResourceManager.GetString("DOFRAMEDPREIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOFRAMEDPREUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOFRAMEDPREUP {
            get {
                return ResourceManager.GetString("DOFRAMEDPREUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOGREENLAMP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOGREENLAMP {
            get {
                return ResourceManager.GetString("DOGREENLAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOINKERDOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOINKERDOWN {
            get {
                return ResourceManager.GetString("DOINKERDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOINKERSHOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOINKERSHOT {
            get {
                return ResourceManager.GetString("DOINKERSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOINKERSHOTEX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOINKERSHOTEX {
            get {
                return ResourceManager.GetString("DOINKERSHOTEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOINSPECTION_COVER_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOINSPECTION_COVER_LOCK {
            get {
                return ResourceManager.GetString("DOINSPECTION_COVER_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOLATCH_CMD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOLATCH_CMD {
            get {
                return ResourceManager.GetString("DOLATCH_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOLDOOR_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOLDOOR_LOCK {
            get {
                return ResourceManager.GetString("DOLDOOR_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOLDRY_AIR_ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOLDRY_AIR_ON {
            get {
                return ResourceManager.GetString("DOLDRY_AIR_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOLOADERDOOR_CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOLOADERDOOR_CLOSE {
            get {
                return ResourceManager.GetString("DOLOADERDOOR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOLOADERDOOR_OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOLOADERDOOR_OPEN {
            get {
                return ResourceManager.GetString("DOLOADERDOOR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMANI_CON_ENABLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMANI_CON_ENABLE {
            get {
                return ResourceManager.GetString("DOMANI_CON_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMANIPULATOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMANIPULATOR {
            get {
                return ResourceManager.GetString("DOMANIPULATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMUX_ENABLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMUX_ENABLE {
            get {
                return ResourceManager.GetString("DOMUX_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMUX_SIGNAL0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMUX_SIGNAL0 {
            get {
                return ResourceManager.GetString("DOMUX_SIGNAL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMUX_SIGNAL1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMUX_SIGNAL1 {
            get {
                return ResourceManager.GetString("DOMUX_SIGNAL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOMUX_SIGNAL2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOMUX_SIGNAL2 {
            get {
                return ResourceManager.GetString("DOMUX_SIGNAL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DONEEDLE_BRUSH_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DONEEDLE_BRUSH_UP {
            get {
                return ResourceManager.GetString("DONEEDLE_BRUSH_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DONEEDLECLEANAIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DONEEDLECLEANAIRON {
            get {
                return ResourceManager.GetString("DONEEDLECLEANAIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DONMC_COMM_RESET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DONMC_COMM_RESET {
            get {
                return ResourceManager.GetString("DONMC_COMM_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOOCR1LIGHT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOOCR1LIGHT {
            get {
                return ResourceManager.GetString("DOOCR1LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOOCR2LIGHT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOOCR2LIGHT {
            get {
                return ResourceManager.GetString("DOOCR2LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOOCR3LIGHT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOOCR3LIGHT {
            get {
                return ResourceManager.GetString("DOOCR3LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPACL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPACL {
            get {
                return ResourceManager.GetString("DOPACL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPRE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPRE {
            get {
                return ResourceManager.GetString("DOPRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPREALIGNCAM_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPREALIGNCAM_0 {
            get {
                return ResourceManager.GetString("DOPREALIGNCAM_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPREALIGNCAM_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPREALIGNCAM_1 {
            get {
                return ResourceManager.GetString("DOPREALIGNCAM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPREALIGNORGSW_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPREALIGNORGSW_0 {
            get {
                return ResourceManager.GetString("DOPREALIGNORGSW_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOPREALIGNORGSW_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOPREALIGNORGSW_1 {
            get {
                return ResourceManager.GetString("DOPREALIGNORGSW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOREDLAMP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOREDLAMP {
            get {
                return ResourceManager.GetString("DOREDLAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOREDLAMPON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOREDLAMPON {
            get {
                return ResourceManager.GetString("DOREDLAMPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DORESETAMP_0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DORESETAMP_0 {
            get {
                return ResourceManager.GetString("DORESETAMP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DORESETAMP_1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DORESETAMP_1 {
            get {
                return ResourceManager.GetString("DORESETAMP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSACCENABLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOSACCENABLE {
            get {
                return ResourceManager.GetString("DOSACCENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSCAN_SENSOR_OUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOSCAN_SENSOR_OUT {
            get {
                return ResourceManager.GetString("DOSCAN_SENSOR_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSCANLIGHT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOSCANLIGHT {
            get {
                return ResourceManager.GetString("DOSCANLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSERVICE_MANI_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOSERVICE_MANI_LOCK {
            get {
                return ResourceManager.GetString("DOSERVICE_MANI_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSUBCHUCKAIRON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOSUBCHUCKAIRON {
            get {
                return ResourceManager.GetString("DOSUBCHUCKAIRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOT2K_CYLINDER_DOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOT2K_CYLINDER_DOWN {
            get {
                return ResourceManager.GetString("DOT2K_CYLINDER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOT2K_CYLINDER_MID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOT2K_CYLINDER_MID {
            get {
                return ResourceManager.GetString("DOT2K_CYLINDER_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOT2K_CYLINDER_UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOT2K_CYLINDER_UP {
            get {
                return ResourceManager.GetString("DOT2K_CYLINDER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTESTER_HEAD_LOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTESTER_HEAD_LOCK {
            get {
                return ResourceManager.GetString("DOTESTER_HEAD_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTESTER_HEAD_UNLOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTESTER_HEAD_UNLOCK {
            get {
                return ResourceManager.GetString("DOTESTER_HEAD_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTHREELEGDOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTHREELEGDOWN {
            get {
                return ResourceManager.GetString("DOTHREELEGDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTHREELEGUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTHREELEGUP {
            get {
                return ResourceManager.GetString("DOTHREELEGUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTHREEPOD_COOLING_ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTHREEPOD_COOLING_ON {
            get {
                return ResourceManager.GetString("DOTHREEPOD_COOLING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTP_LOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTP_LOCK_REQ {
            get {
                return ResourceManager.GetString("DOTP_LOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTP_UNLOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTP_UNLOCK_REQ {
            get {
                return ResourceManager.GetString("DOTP_UNLOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOTRIGGEROUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOTRIGGEROUT {
            get {
                return ResourceManager.GetString("DOTRIGGEROUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOUNLATCH_CMD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOUNLATCH_CMD {
            get {
                return ResourceManager.GetString("DOUNLATCH_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOVMUX_SIGNAL0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOVMUX_SIGNAL0 {
            get {
                return ResourceManager.GetString("DOVMUX_SIGNAL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOVMUX_SIGNAL1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOVMUX_SIGNAL1 {
            get {
                return ResourceManager.GetString("DOVMUX_SIGNAL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOVMUX_SIGNAL2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOVMUX_SIGNAL2 {
            get {
                return ResourceManager.GetString("DOVMUX_SIGNAL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOWAFERMIDDLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOWAFERMIDDLE {
            get {
                return ResourceManager.GetString("DOWAFERMIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOWAFERREAR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOWAFERREAR {
            get {
                return ResourceManager.GetString("DOWAFERREAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOYELLOWLAMP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOYELLOWLAMP {
            get {
                return ResourceManager.GetString("DOYELLOWLAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOYELLOWLAMPON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOYELLOWLAMPON {
            get {
                return ResourceManager.GetString("DOYELLOWLAMPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOZIF_LOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOZIF_LOCK_REQ {
            get {
                return ResourceManager.GetString("DOZIF_LOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOZIF_UNLOCK_REQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOZIF_UNLOCK_REQ {
            get {
                return ResourceManager.GetString("DOZIF_UNLOCK_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOZUPLAMPON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DOZUPLAMPON {
            get {
                return ResourceManager.GetString("DOZUPLAMPON", resourceCulture);
            }
        }
    }
}
