//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPadStandardModule.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAPadStandardModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Auto Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoSearch {
            get {
                return ResourceManager.GetString("AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Align {
            get {
                return ResourceManager.GetString("Btn_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutoPad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_AutoPadSize {
            get {
                return ResourceManager.GetString("Btn_AutoPadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_DeleteAll {
            get {
                return ResourceManager.GetString("Btn_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Focus {
            get {
                return ResourceManager.GetString("Btn_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing the Teachdie initializes the pad data. Do you want to proceed?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Change_TeachDie_Message {
            get {
                return ResourceManager.GetString("Change_TeachDie_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteAllPad {
            get {
                return ResourceManager.GetString("DeleteAllPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeletePad {
            get {
                return ResourceManager.GetString("DeletePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pad is not in the delete area. Please check the pad position again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeletePadErrorMessage {
            get {
                return ResourceManager.GetString("DeletePadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Delete Pad.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeletePadErrorTitile {
            get {
                return ResourceManager.GetString("DeletePadErrorTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WaferAlign must be done before registering the pad. Please use Align first to register the pad.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoWaferAlignErrorMessage {
            get {
                return ResourceManager.GetString("DoWaferAlignErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Registe Pad. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoWaferAlignErrorTitle {
            get {
                return ResourceManager.GetString("DoWaferAlignErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DrawPad {
            get {
                return ResourceManager.GetString("DrawPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Move_Teach_Die {
            get {
                object obj = ResourceManager.GetObject("Move_Teach_Die", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Failed to find pad. Please change the lighting settings or adjust the pad position and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MoveToPad_Blob_ErrorMessage {
            get {
                return ResourceManager.GetString("MoveToPad_Blob_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PadRegistrationHeader {
            get {
                return ResourceManager.GetString("PadRegistrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PadUpdateHeader {
            get {
                return ResourceManager.GetString("PadUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ref Pad Teaching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoveryHeader {
            get {
                return ResourceManager.GetString("RecoveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pad registration range is out of range.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegistePadRangeErrorMessage {
            get {
                return ResourceManager.GetString("RegistePadRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisteredPad {
            get {
                return ResourceManager.GetString("RegisteredPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterPad {
            get {
                return ResourceManager.GetString("RegisterPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UIModeChangePriviliage {
            get {
                return ResourceManager.GetString("UIModeChangePriviliage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
    }
}
