namespace MapConverterModule.E142.Format
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     이 코드는 도구를 사용하여 생성되었습니다.
    //     런타임 버전:4.0.30319.42000
    //
    //     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
    //     이러한 변경 내용이 손실됩니다.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // 이 소스 코드는 xsd, 버전=4.8.3928.0에서 자동 생성되었습니다.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    [System.Xml.Serialization.XmlRootAttribute("MapData", Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap", IsNullable = false)]
    public partial class MapDataType
    {
        private LayoutType[] layoutsField;

        private SubstrateType[] substratesField;

        private SubstrateMapType[] substrateMapsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Layout", IsNullable = false)]
        public LayoutType[] Layouts
        {
            get
            {
                return this.layoutsField;
            }
            set
            {
                this.layoutsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Substrate", IsNullable = false)]
        public SubstrateType[] Substrates
        {
            get
            {
                return this.substratesField;
            }
            set
            {
                this.substratesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SubstrateMap", IsNullable = false)]
        public SubstrateMapType[] SubstrateMaps
        {
            get
            {
                return this.substrateMapsField;
            }
            set
            {
                this.substrateMapsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class LayoutType
    {

        private LogicalCoordinatesType dimensionField;

        private PhysicalCoordinatesType lowerLeftField;

        private PhysicalCoordinatesType deviceSizeField;

        private PhysicalCoordinatesType stepSizeField;

        private ZDimensionsType zField;

        private string topImageField;

        private string bottomImageField;

        private string productIdField;

        private ChildLayoutType[] childLayoutsField;

        private string layoutIdField;

        private string defaultUnitsField;

        private bool topLevelField;

        public LayoutType()
        {
            this.topLevelField = false;
        }

        /// <remarks/>
        public LogicalCoordinatesType Dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }

        /// <remarks/>
        public PhysicalCoordinatesType LowerLeft
        {
            get
            {
                return this.lowerLeftField;
            }
            set
            {
                this.lowerLeftField = value;
            }
        }

        /// <remarks/>
        public PhysicalCoordinatesType DeviceSize
        {
            get
            {
                return this.deviceSizeField;
            }
            set
            {
                this.deviceSizeField = value;
            }
        }

        /// <remarks/>
        public PhysicalCoordinatesType StepSize
        {
            get
            {
                return this.stepSizeField;
            }
            set
            {
                this.stepSizeField = value;
            }
        }

        /// <remarks/>
        public ZDimensionsType Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }

        /// <remarks/>
        public string TopImage
        {
            get
            {
                return this.topImageField;
            }
            set
            {
                this.topImageField = value;
            }
        }

        /// <remarks/>
        public string BottomImage
        {
            get
            {
                return this.bottomImageField;
            }
            set
            {
                this.bottomImageField = value;
            }
        }

        /// <remarks/>
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChildLayout", IsNullable = false)]
        public ChildLayoutType[] ChildLayouts
        {
            get
            {
                return this.childLayoutsField;
            }
            set
            {
                this.childLayoutsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayoutId
        {
            get
            {
                return this.layoutIdField;
            }
            set
            {
                this.layoutIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultUnits
        {
            get
            {
                return this.defaultUnitsField;
            }
            set
            {
                this.defaultUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TopLevel
        {
            get
            {
                return this.topLevelField;
            }
            set
            {
                this.topLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class LogicalCoordinatesType
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class TransferType
    {

        private string fxField;

        private string fyField;

        private string txField;

        private string tyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string FX
        {
            get
            {
                return this.fxField;
            }
            set
            {
                this.fxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string FY
        {
            get
            {
                return this.fyField;
            }
            set
            {
                this.fyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TX
        {
            get
            {
                return this.txField;
            }
            set
            {
                this.txField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TY
        {
            get
            {
                return this.tyField;
            }
            set
            {
                this.tyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class TransferMapType
    {

        private TransferType[] tField;

        private SubstrateTypeEnum fromSubstrateTypeField;

        private string fromSubstrateIdField;

        private string fromSubstrateLayoutSpecifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T")]
        public TransferType[] T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubstrateTypeEnum FromSubstrateType
        {
            get
            {
                return this.fromSubstrateTypeField;
            }
            set
            {
                this.fromSubstrateTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromSubstrateId
        {
            get
            {
                return this.fromSubstrateIdField;
            }
            set
            {
                this.fromSubstrateIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FromSubstrateLayoutSpecifier
        {
            get
            {
                return this.fromSubstrateLayoutSpecifierField;
            }
            set
            {
                this.fromSubstrateLayoutSpecifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum SubstrateTypeEnum
    {

        /// <remarks/>
        Wafer,

        /// <remarks/>
        Frame,

        /// <remarks/>
        Strip,

        /// <remarks/>
        Tray,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class DeviceIdMapType
    {

        private DeviceIdType[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id")]
        public DeviceIdType[] Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class DeviceIdType
    {

        private string xField;

        private string yField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class BinCodeType
    {

        private string xField;

        private string yField;

        private string numberField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class BinDefinitionType
    {

        private string binCodeField;

        private string binCountField;

        private string binQualityField;

        private string binDescriptionField;

        private bool pickField;

        public BinDefinitionType()
        {
            this.binQualityField = "";
            this.binDescriptionField = "";
            this.pickField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BinCode
        {
            get
            {
                return this.binCodeField;
            }
            set
            {
                this.binCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string BinCount
        {
            get
            {
                return this.binCountField;
            }
            set
            {
                this.binCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string BinQuality
        {
            get
            {
                return this.binQualityField;
            }
            set
            {
                this.binQualityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string BinDescription
        {
            get
            {
                return this.binDescriptionField;
            }
            set
            {
                this.binDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Pick
        {
            get
            {
                return this.pickField;
            }
            set
            {
                this.pickField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class BinCodeMapType
    {

        private BinDefinitionType[] binDefinitionsField;

        private BinCodeType[] binCodeField;

        private BinTypeEnum binTypeField;

        private string nullBinField;

        private MapTypeEnum mapTypeField;

        private bool mapTypeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("BinDefinition", IsNullable = false)]
        public BinDefinitionType[] BinDefinitions
        {
            get
            {
                return this.binDefinitionsField;
            }
            set
            {
                this.binDefinitionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BinCode")]
        public BinCodeType[] BinCode
        {
            get
            {
                return this.binCodeField;
            }
            set
            {
                this.binCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BinTypeEnum BinType
        {
            get
            {
                return this.binTypeField;
            }
            set
            {
                this.binTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NullBin
        {
            get
            {
                return this.nullBinField;
            }
            set
            {
                this.nullBinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MapTypeEnum MapType
        {
            get
            {
                return this.mapTypeField;
            }
            set
            {
                this.mapTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MapTypeSpecified
        {
            get
            {
                return this.mapTypeFieldSpecified;
            }
            set
            {
                this.mapTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum BinTypeEnum
    {

        /// <remarks/>
        Ascii,

        /// <remarks/>
        Decimal,

        /// <remarks/>
        HexaDecimal,

        /// <remarks/>
        Integer2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum MapTypeEnum
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2DArray")]
        Item2DArray,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Row/Column")]
        RowColumn,

        /// <remarks/>
        Array,

        /// <remarks/>
        Coordinate,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class ReferenceDeviceType
    {

        private LogicalCoordinatesType coordinatesField;

        private PhysicalCoordinatesType positionField;

        private string nameField;

        public ReferenceDeviceType()
        {
            this.nameField = "";
        }

        /// <remarks/>
        public LogicalCoordinatesType Coordinates
        {
            get
            {
                return this.coordinatesField;
            }
            set
            {
                this.coordinatesField = value;
            }
        }

        /// <remarks/>
        public PhysicalCoordinatesType Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class PhysicalCoordinatesType
    {

        private double xField;

        private double yField;

        private string unitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class OverlayType
    {

        private ReferenceDeviceType[] referenceDevicesField;

        private object[] itemsField;

        private string mapNameField;

        private string mapVersionField;

        public OverlayType()
        {
            this.mapVersionField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenceDevice", IsNullable = false)]
        public ReferenceDeviceType[] ReferenceDevices
        {
            get
            {
                return this.referenceDevicesField;
            }
            set
            {
                this.referenceDevicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BinCodeMap", typeof(BinCodeMapType))]
        [System.Xml.Serialization.XmlElementAttribute("DeviceIdMap", typeof(DeviceIdMapType))]
        [System.Xml.Serialization.XmlElementAttribute("TransferMap", typeof(TransferMapType))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MapName
        {
            get
            {
                return this.mapNameField;
            }
            set
            {
                this.mapNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string MapVersion
        {
            get
            {
                return this.mapVersionField;
            }
            set
            {
                this.mapVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class SubstrateMapType
    {

        private OverlayType[] overlayField;

        private SubstrateTypeEnum substrateTypeField;

        private string substrateIdField;

        private string layoutSpecifierField;

        private SubstrateSideEnum substrateSideField;

        private string orientationField;

        private OriginLocationEnum originLocationField;

        private AxisDirectionEnum axisDirectionField;

        public SubstrateMapType()
        {
            this.substrateSideField = SubstrateSideEnum.TopSide;
            this.orientationField = "0";
            this.originLocationField = OriginLocationEnum.LowerLeft;
            this.axisDirectionField = AxisDirectionEnum.UpRight;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Overlay")]
        public OverlayType[] Overlay
        {
            get
            {
                return this.overlayField;
            }
            set
            {
                this.overlayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubstrateTypeEnum SubstrateType
        {
            get
            {
                return this.substrateTypeField;
            }
            set
            {
                this.substrateTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubstrateId
        {
            get
            {
                return this.substrateIdField;
            }
            set
            {
                this.substrateIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayoutSpecifier
        {
            get
            {
                return this.layoutSpecifierField;
            }
            set
            {
                this.layoutSpecifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SubstrateSideEnum.TopSide)]
        public SubstrateSideEnum SubstrateSide
        {
            get
            {
                return this.substrateSideField;
            }
            set
            {
                this.substrateSideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string Orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OriginLocationEnum.LowerLeft)]
        public OriginLocationEnum OriginLocation
        {
            get
            {
                return this.originLocationField;
            }
            set
            {
                this.originLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AxisDirectionEnum.UpRight)]
        public AxisDirectionEnum AxisDirection
        {
            get
            {
                return this.axisDirectionField;
            }
            set
            {
                this.axisDirectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum SubstrateSideEnum
    {
        /// <remarks/>
        TopSide,

        /// <remarks/>
        BottomSide,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum OriginLocationEnum
    {

        /// <remarks/>
        LowerLeft,

        /// <remarks/>
        UpperLeft,

        /// <remarks/>
        LowerRight,

        /// <remarks/>
        UpperRight,

        /// <remarks/>
        Center,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public enum AxisDirectionEnum
    {

        /// <remarks/>
        UpRight,

        /// <remarks/>
        DownRight,

        /// <remarks/>
        UpLeft,

        /// <remarks/>
        DownLeft,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class AliasIdType
    {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class SubstrateType
    {

        private string lotIdField;

        private AliasIdType[] aliasIdsField;

        private string carrierTypeField;

        private string carrierIdField;

        private string slotNumberField;

        private string substrateNumberField;

        private string goodDevicesField;

        private string supplierNameField;

        private string statusField;

        private SubstrateTypeEnum substrateType1Field;

        private string substrateIdField;

        /// <remarks/>
        public string LotId
        {
            get
            {
                return this.lotIdField;
            }
            set
            {
                this.lotIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AliasId", IsNullable = false)]
        public AliasIdType[] AliasIds
        {
            get
            {
                return this.aliasIdsField;
            }
            set
            {
                this.aliasIdsField = value;
            }
        }

        /// <remarks/>
        public string CarrierType
        {
            get
            {
                return this.carrierTypeField;
            }
            set
            {
                this.carrierTypeField = value;
            }
        }

        /// <remarks/>
        public string CarrierId
        {
            get
            {
                return this.carrierIdField;
            }
            set
            {
                this.carrierIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string SlotNumber
        {
            get
            {
                return this.slotNumberField;
            }
            set
            {
                this.slotNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string SubstrateNumber
        {
            get
            {
                return this.substrateNumberField;
            }
            set
            {
                this.substrateNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string GoodDevices
        {
            get
            {
                return this.goodDevicesField;
            }
            set
            {
                this.goodDevicesField = value;
            }
        }

        /// <remarks/>
        public string SupplierName
        {
            get
            {
                return this.supplierNameField;
            }
            set
            {
                this.supplierNameField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("SubstrateType")]
        public SubstrateTypeEnum SubstrateType1
        {
            get
            {
                return this.substrateType1Field;
            }
            set
            {
                this.substrateType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubstrateId
        {
            get
            {
                return this.substrateIdField;
            }
            set
            {
                this.substrateIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class ChildLayoutType
    {
        private string layoutIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayoutId
        {
            get
            {
                return this.layoutIdField;
            }
            set
            {
                this.layoutIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:semi-org:xsd.E142-1.V0211.SubstrateMap")]
    public partial class ZDimensionsType
    {

        private string orderField;

        private double heightField;

        private string unitsField;

        public ZDimensionsType()
        {
            this.orderField = "0";
            this.heightField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }
}






