//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProberViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProberViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Acceptable range of all contact to overdrive :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AcceptableRangeOfAllToOverdrive {
            get {
                return ResourceManager.GetString("AcceptableRangeOfAllToOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acceptable range of first contact to all contact :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AcceptableRangeOfFirstToAllContact {
            get {
                return ResourceManager.GetString("AcceptableRangeOfFirstToAllContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acceptable range of first contact to overdrive :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AcceptableRangeOfFirstToOverdrive {
            get {
                return ResourceManager.GetString("AcceptableRangeOfFirstToOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACCOUNT CREATE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACCOUNT SETTING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountSetting {
            get {
                return ResourceManager.GetString("AccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALIGN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ALIGN {
            get {
                return ResourceManager.GetString("ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string alignment {
            get {
                return ResourceManager.GetString("alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Contact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllContact {
            get {
                return ResourceManager.GetString("AllContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Arm {
            get {
                object obj = ResourceManager.GetObject("Arm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Buffer {
            get {
                object obj = ResourceManager.GetObject("Buffer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Cardbuffer {
            get {
                object obj = ResourceManager.GetObject("Cardbuffer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Change Probe Card과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CardChange {
            get {
                return ResourceManager.GetString("CardChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap CardHand {
            get {
                object obj = ResourceManager.GetObject("CardHand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap CardTray {
            get {
                object obj = ResourceManager.GetObject("CardTray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cassette Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CassettePort {
            get {
                return ResourceManager.GetString("CassettePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Cell {
            get {
                object obj = ResourceManager.GetObject("Cell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Change Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeDevice {
            get {
                return ResourceManager.GetString("ChangeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change ProbeCard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeProbeCard {
            get {
                return ResourceManager.GetString("ChangeProbeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ChuckDown {
            get {
                object obj = ResourceManager.GetObject("ChuckDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ChuckUp {
            get {
                object obj = ResourceManager.GetObject("ChuckUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cleanpad Cleaning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CleanPadCleaning {
            get {
                return ResourceManager.GetString("CleanPadCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Clean Pad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CleanSheetChange {
            get {
                return ResourceManager.GetString("CleanSheetChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Manual Probe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContactCheck {
            get {
                return ResourceManager.GetString("ContactCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue Probing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinueProbing {
            get {
                return ResourceManager.GetString("ContinueProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue Lot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinuousLot {
            get {
                return ResourceManager.GetString("ContinuousLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateNewDevice {
            get {
                return ResourceManager.GetString("CreateNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current All Contact Height :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentAllContactHeight {
            get {
                return ResourceManager.GetString("CurrentAllContactHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current First Contact Height :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentFirstContactHeight {
            get {
                return ResourceManager.GetString("CurrentFirstContactHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yield과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurYield {
            get {
                return ResourceManager.GetString("CurYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not recover after deleting all sequences. Are you sure you want to delete?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteAllSeqMessage {
            get {
                return ResourceManager.GetString("DeleteAllSeqMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceChange {
            get {
                return ResourceManager.GetString("DeviceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceSetting {
            get {
                return ResourceManager.GetString("DeviceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Y Axis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisableYAxis {
            get {
                return ResourceManager.GetString("DisableYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance between First And All Contact :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DistanceToAllFromFirstContact {
            get {
                return ResourceManager.GetString("DistanceToAllFromFirstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH Docking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Docking {
            get {
                return ResourceManager.GetString("Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Y Axis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnableYAxis {
            get {
                return ResourceManager.GetString("EnableYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Contact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FirstContact {
            get {
                return ResourceManager.GetString("FirstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap FOUP {
            get {
                object obj = ResourceManager.GetObject("FOUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Go to download page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoToDownLoadPage {
            get {
                return ResourceManager.GetString("GoToDownLoadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load_CST {
            get {
                return ResourceManager.GetString("Load_CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Loader {
            get {
                object obj = ResourceManager.GetObject("Loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Loader Initialization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoaderInitialization {
            get {
                return ResourceManager.GetString("LoaderInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SnapShot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOT {
            get {
                return ResourceManager.GetString("LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOT START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOT_START {
            get {
                return ResourceManager.GetString("LOT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOT start description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOT_START_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOT_START_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot End과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LotEnd {
            get {
                return ResourceManager.GetString("LotEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOT MENU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOTMENU {
            get {
                return ResourceManager.GetString("LOTMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot Statistics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LotStatistics {
            get {
                return ResourceManager.GetString("LotStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine Initialization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MachineInitialization {
            get {
                return ResourceManager.GetString("MachineInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create sequence. Please check the setting environment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MakeSequenceFailMessage {
            get {
                return ResourceManager.GetString("MakeSequenceFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management (Copy / Remove)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string management_Copy_Remove {
            get {
                return ResourceManager.GetString("management_Copy_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual Align과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManualAlign {
            get {
                return ResourceManager.GetString("ManualAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manaul Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManualMode {
            get {
                return ResourceManager.GetString("ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual Probe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManualProbe {
            get {
                return ResourceManager.GetString("ManualProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual Retry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManualRetry {
            get {
                return ResourceManager.GetString("ManualRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manaul Reverse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManualReverse {
            get {
                return ResourceManager.GetString("ManualReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MENU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOTION CONTROL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MotionControl {
            get {
                return ResourceManager.GetString("MotionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motion Jog과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MotionJog {
            get {
                return ResourceManager.GetString("MotionJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi-Pass Probing (CP2)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MultiPassProbing {
            get {
                return ResourceManager.GetString("MultiPassProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NC Pad Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NCPadChange {
            get {
                return ResourceManager.GetString("NCPadChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Needle Cleaning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NeedleCleaning {
            get {
                return ResourceManager.GetString("NeedleCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Probing (CP1)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NormalProbing {
            get {
                return ResourceManager.GetString("NormalProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set up dut first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotExistDutErrorMessage {
            get {
                return ResourceManager.GetString("NotExistDutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wafer does not exist. Please proceed after wafer loading.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotExistWaferMessage {
            get {
                return ResourceManager.GetString("NotExistWaferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPERATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OPERATION {
            get {
                return ResourceManager.GetString("OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OPName {
            get {
                return ResourceManager.GetString("OPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overdrive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overdrive Low Limit :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OverdriveLowLimit {
            get {
                return ResourceManager.GetString("OverdriveLowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap PA {
            get {
                object obj = ResourceManager.GetObject("PA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Pass Die Probing (CP2)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PassDieProbing {
            get {
                return ResourceManager.GetString("PassDieProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PinAlign {
            get {
                return ResourceManager.GetString("PinAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMI Viewer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PMIViewer {
            get {
                return ResourceManager.GetString("PMIViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polish Wafer Cleaning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PolishWaferCleaning {
            get {
                return ResourceManager.GetString("PolishWaferCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PolishWaferInformaiton {
            get {
                return ResourceManager.GetString("PolishWaferInformaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Probe Card과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProbeCardChange {
            get {
                return ResourceManager.GetString("ProbeCardChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RECIPE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result Map Viewer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResultMapViewer {
            get {
                return ResourceManager.GetString("ResultMapViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Scan_CST {
            get {
                return ResourceManager.GetString("Scan_CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap selecteicon {
            get {
                object obj = ResourceManager.GetObject("selecteicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingChange {
            get {
                return ResourceManager.GetString("SettingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SETUP {
            get {
                return ResourceManager.GetString("SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETUP RECIPE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetupRecipe {
            get {
                return ResourceManager.GetString("SetupRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHUTDOWN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slot Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SlotNum {
            get {
                return ResourceManager.GetString("SlotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snapshot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SnapShot {
            get {
                return ResourceManager.GetString("SnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soaking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Soaking {
            get {
                return ResourceManager.GetString("Soaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATISTICS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After First Probe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterFirstProbe {
            get {
                return ResourceManager.GetString("StopAfterFirstProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After Load CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterLoadCST {
            get {
                return ResourceManager.GetString("StopAfterLoadCST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After Load CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterLoadCST1 {
            get {
                return ResourceManager.GetString("StopAfterLoadCST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After OCR Process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterOCRProcess {
            get {
                return ResourceManager.GetString("StopAfterOCRProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After Probe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterProbe {
            get {
                return ResourceManager.GetString("StopAfterProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop After Wafer Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopAfterWaferLoad {
            get {
                return ResourceManager.GetString("StopAfterWaferLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Before Probe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopBeforeProbe {
            get {
                return ResourceManager.GetString("StopBeforeProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Before Retest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopBeforeRetest {
            get {
                return ResourceManager.GetString("StopBeforeRetest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact Limits과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_ContactLimits {
            get {
                return ResourceManager.GetString("Str_ContactLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple Contact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_MultipleContactSetting {
            get {
                return ResourceManager.GetString("Str_MultipleContactSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z clearance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_ZClearanceAndOverdrive {
            get {
                return ResourceManager.GetString("Str_ZClearanceAndOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z Soft Touch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_ZSoftTouch {
            get {
                return ResourceManager.GetString("Str_ZSoftTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z Clearance &amp; Overdriver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MACHINE INIT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SysInit {
            get {
                return ResourceManager.GetString("SysInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SYSTEM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TaskManagement {
            get {
                return ResourceManager.GetString("TaskManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current temperature and the set temperature are not the same. Please check the temperature.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempErrorMessage {
            get {
                return ResourceManager.GetString("TempErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempErrorTitle {
            get {
                return ResourceManager.GetString("TempErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operate Tester Head과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TesterHeadChange {
            get {
                return ResourceManager.GetString("TesterHeadChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tester Head Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TesterHeadUnlock {
            get {
                return ResourceManager.GetString("TesterHeadUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thread Lock Explorer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThreadLockExplorer {
            get {
                return ResourceManager.GetString("ThreadLockExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer Wafer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TransferWafer {
            get {
                return ResourceManager.GetString("TransferWafer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string turnoff {
            get {
                return ResourceManager.GetString("turnoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH Undocking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Undocking {
            get {
                return ResourceManager.GetString("Undocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unload CST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unload_CST {
            get {
                return ResourceManager.GetString("Unload_CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload/Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Upload_Download {
            get {
                return ResourceManager.GetString("Upload_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UTILITY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wafer Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaferAlign {
            get {
                return ResourceManager.GetString("WaferAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set up waferalign first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaferAlignSetupErrorMessage {
            get {
                return ResourceManager.GetString("WaferAlignSetupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wafer Handling과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaferHandling {
            get {
                return ResourceManager.GetString("WaferHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wafer ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaferID {
            get {
                return ResourceManager.GetString("WaferID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wafer Inspection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaferInspection {
            get {
                return ResourceManager.GetString("WaferInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningMessageTitle {
            get {
                return ResourceManager.GetString("WarningMessageTitle", resourceCulture);
            }
        }
    }
}
