//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHighStandardModule.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHighStandardModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Apply High Alignment Infomation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdSettingCloseWaitMessage {
            get {
                return ResourceManager.GetString("AdSettingCloseWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply HeightProfiling Failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplyHeightProfilingErrorMessage {
            get {
                return ResourceManager.GetString("ApplyHeightProfilingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Alignment Failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HighFailMessage {
            get {
                return ResourceManager.GetString("HighFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Alignment Succeed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HighSuccessMessage {
            get {
                return ResourceManager.GetString("HighSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoMessageTitle {
            get {
                return ResourceManager.GetString("InfoMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter it as a positive number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string JumpIndexMinusError {
            get {
                return ResourceManager.GetString("JumpIndexMinusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The JumpIndex you entered is not available. Do you want to automatically find JumpIndex?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string JumpIndexThetaAlignErrorMessage {
            get {
                return ResourceManager.GetString("JumpIndexThetaAlignErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenFlyout {
            get {
                return ResourceManager.GetString("OpenFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Acceptance value must be less than the Certainty value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PMAcceptanceLimitError {
            get {
                return ResourceManager.GetString("PMAcceptanceLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Certainty value must be greater than the Acceptance value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PMCertaintyLimitError {
            get {
                return ResourceManager.GetString("PMCertaintyLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can be set from 50 to 100.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PMValueSettingLimitError {
            get {
                return ResourceManager.GetString("PMValueSettingLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Pattern Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoveryHeader {
            get {
                return ResourceManager.GetString("RecoveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Pattern과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterPattern {
            get {
                return ResourceManager.GetString("RegisterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Pattern 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterPattern1 {
            get {
                return ResourceManager.GetString("RegisterPattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UIModeChangePriviliage {
            get {
                return ResourceManager.GetString("UIModeChangePriviliage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WaitTitle {
            get {
                return ResourceManager.GetString("WaitTitle", resourceCulture);
            }
        }
    }
}
