//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAIndexAlignEdgeModule.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAIndexAlignEdgeModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ArrowLeft_Edge {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft_Edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ArrowLeft_PT {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft_PT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ArrowRight_Edge {
            get {
                object obj = ResourceManager.GetObject("ArrowRight_Edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ArrowRight_PT {
            get {
                object obj = ResourceManager.GetObject("ArrowRight_PT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please try again with WaferLow camera.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CameraErrorMessage {
            get {
                return ResourceManager.GetString("CameraErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Edge_LeftBottom {
            get {
                object obj = ResourceManager.GetObject("Edge_LeftBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Edge_LeftUpper {
            get {
                object obj = ResourceManager.GetObject("Edge_LeftUpper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Edge_RightBottom {
            get {
                object obj = ResourceManager.GetObject("Edge_RightBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Edge_RightUpper {
            get {
                object obj = ResourceManager.GetObject("Edge_RightUpper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please try again with a different Position Edge.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EdgeFindFailMessage {
            get {
                return ResourceManager.GetString("EdgeFindFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail Find Edge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EdgeFindFailTitle {
            get {
                return ResourceManager.GetString("EdgeFindFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge Succeed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EdgeSuccessMessage {
            get {
                return ResourceManager.GetString("EdgeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge Index Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IndexAlign Failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IndexAlignFailMessage {
            get {
                return ResourceManager.GetString("IndexAlignFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the pattern of the lower left edge position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterLowerLeftMessage {
            get {
                return ResourceManager.GetString("RegisterLowerLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the pattern of the lower right edge position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterLowerRightMessage {
            get {
                return ResourceManager.GetString("RegisterLowerRightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration is available only on MarkDie.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterPosNotMarkDieErrorMessage {
            get {
                return ResourceManager.GetString("RegisterPosNotMarkDieErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set pattern of upper left  edge position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterUpperLeftMessage {
            get {
                return ResourceManager.GetString("RegisterUpperLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the pattern of the upper right edge position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisterUpperRightMessage {
            get {
                return ResourceManager.GetString("RegisterUpperRightMessage", resourceCulture);
            }
        }
    }
}
